version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    networks:
      - web
    labels:
      - "traefik.http.routers.$HOSTNAME-https.entrypoints=https"
      - "traefik.http.routers.$HOSTNAME-https.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.$HOSTNAME-https.tls=true"
      - "traefik.http.routers.$HOSTNAME-https.tls.certresolver=letsencrypt"
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true