version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    container_name: ${NAME}
    networks:
      - web
    labels:
      traefik.enable: "true"
      traefik.http.routers.service-http.rule: "Host(`statik.keops.io`)"
      traefik.http.routers.service-http.entrypoints: "http"
      traefik.http.routers.service-http.middlewares: "https-redirect@file"
      traefik.http.routers.service-https.rule: "Host(`statik.keops.io`)"
      traefik.http.routers.service-https.entrypoints: "https"
      traefik.http.routers.service-https.middlewares: "security@file, compression@file"
      traefik.http.routers.service-https.tls: "true"
      traefik.http.routers.service-https.tls.certresolver: "letsencrypt"
    volumes:
      - ./hugo/public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true