version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    container_name: ${HOST}
    networks:
      - web
    labels:
      - "traefik.http.routers.${HOST}.entrypoints=https"
      - "traefik.http.routers.${HOST}.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.${HOST}.tls=true"
      - "traefik.http.routers.${HOST}.tls.certresolver=letsencrypt"
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true