version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    container_name: statik
    restart: always
    networks:
      - web
    labels:
      - traefik.http.routers.STATIK-SERVICE-http.entrypoints=insecure
      - traefik.http.routers.STATIK-SERVICE-http.rule=Host(`statik.keops.io`)
      
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.STATIK-SERVICE-http.middlewares=https-redirect@docker
      
      - traefik.http.routers.STATIK-SERVICE-https.entrypoints=secure
      - traefik.http.routers.STATIK-SERVICE-https.rule=Host(`statik.keops.io`)
      - traefik.http.routers.STATIK-SERVICE-https.tls=true
      - traefik.http.routers.STATIK-SERVICE-https.tls.certresolver=letsencrypt
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
      - url=statik.keops.io

networks:
  web:
    external: true