version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    networks:
      - web
    labels:
      - "traefik.http.routers.$HOSTNAME.entrypoints=https"
      - "traefik.http.routers.$HOSTNAME.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.$HOSTNAME.tls=true"
      - "traefik.http.routers.$HOSTNAME.tls.certresolver=letsencrypt"
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true