version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    container_name: ${NAME}
    networks:
      - web
    labels:
      - "traefik.http.routers.${NAME}.entrypoints=https"
      - "traefik.http.routers.${NAME}.rule=Host(`$HOSTNAME`)"
      - "traefik.http.routers.${NAME}.tls=true"
      - "traefik.http.routers.${NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${NAME}..middlewares=https-only"
    volumes:
      - ./hugo/public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true