version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    container_name: statik
    restart: always
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.statik.entrypoints=insecure, secure
      - traefik.http.routers.statik.rule=Host(`statik.keops.io`)
      - traefik.http.routers.statik.tls=true
      - traefik.http.routers.statik.tls.certresolver=letsencrypt
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
      - url=statik.keops.io

networks:
  web:
    external: true