version: '2'
services:
  server:
    image: pagespeed/nginx-pagespeed
    restart: always
    networks:
      - web
    labels:
      - traefik.http.routers.statik-https.entrypoints=https
      - traefik.http.routers.statik-https.rule=Host(`$HOSTNAME`)
      - traefik.http.routers.statik-https.tls=true
      - traefik.http.routers.statik-https.tls.certresolver=letsencrypt
    volumes:
      - ./public:/usr/share/nginx/html
    environment:
      - NODE_ENV=production

networks:
  web:
    external: true